name: CrashNativeKit
options:
  bundleIdPrefix: dev.redth.maui.diagnostics.playground
settings:
  base:
    BUILD_LIBRARY_FOR_DISTRIBUTION: YES
    CLANG_ENABLE_MODULES: YES
    CODE_SIGNING_ALLOWED: NO
    COPY_PHASE_STRIP: NO
    DEAD_CODE_STRIPPING: NO
    DEFINES_MODULE: YES
    GENERATE_INFOPLIST_FILE: YES
    GCC_SYMBOLS_PRIVATE_EXTERN: NO
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"
    MACH_O_TYPE: mh_dylib
    SKIP_INSTALL: NO
    STRIP_INSTALLED_PRODUCT: NO
    SUPPORTS_MACCATALYST: YES
targets:
  CrashNativeKit:
    type: framework
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources
      - path: Sources/CrashNativeKit.h
        buildPhase: headers
        headerVisibility: public
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.redth.maui.diagnostics.playground.crashnativekit
        PRODUCT_NAME: CrashNativeKit
